# Site wide configuration

title: Uzem
locale: tr_TR
description: Uzaktan Eğitim Merkezi
logo: site-logo.png
search: true
url: http://devuzem.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site owner
owner:
  name: Uzem
  avatar: bio-photo.png
  email: irtibat@uzem.omu.edu.tr
  disqus-shortname: uzem
  twitter: 
  facebook:
  github: 
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: 
  instagram:
  flickr:
  tumblr:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
